### ISSUE TITLE
LoadError: GeneticVariation.VCF.Reader

### ISSUE THREAD

**Issue by Monete** [compbiocore/VariantVisualization.jl#94] opened 2020-10-08 20:04 UTC
Hi,

I'm writing to ask about an error which appeared to me when I ran VIVA for the first time.

I've ran the **command** below:

<pre>
viva --vcf_file 450exomes-cohort_GENOTYPEGVCF.vcf --output_directory . --save_format html --x_axis_labels --heatmap_title 450exomes-cohort_GENOTYPEGVCF --avg_dp sample,variant
</pre>

So, I've got this **error** here:

```
Welcome to VIVA.

Loading dependency packages:

┌ Warning: ORCA.jl has been deprecated and all savefig functionality
│ has been implemented directly in PlotlyBase itself.
│
│ By implementing in PlotlyBase.jl, the savefig routines are automatically
│ available to PlotlyJS.jl also.
└ @ ORCA ~/.julia/packages/ORCA/U5XaN/src/ORCA.jl:8
...

Finished loading packages!

Reading 450exomes-cohort_notrimmed_COMBINED_GENOTYPEGVCF.vcf ...

ERROR: LoadError: GeneticVariation.VCF.Reader file format error on line 200
Stacktrace:
 [1] error(::String, ::Int64) at ./error.jl:42
 [2] _readheader!(::GeneticVariation.VCF.Reader, ::BioCore.Ragel.State{BufferedStreams.BufferedInputStream{IOStream}}) at /scratch/7411317/.julia/packages/BioCore/YBJvb/src/ReaderHelper.jl:106
 [3] readheader!(::GeneticVariation.VCF.Reader) at /scratch/7411317/.julia/packages/BioCore/YBJvb/src/ReaderHelper.jl:80
 [4] Reader at /scratch/7411317/.julia/packages/GeneticVariation/r8DAL/src/vcf/reader.jl:15 [inlined]
 [5] GeneticVariation.VCF.Reader(::IOStream) at /scratch/7411317/.julia/packages/GeneticVariation/r8DAL/src/vcf/reader.jl:28
 [6] top-level scope at /scratch/7411317/VariantVisualization.jl/viva:131
 [7] include(::Function, ::Module, ::String) at ./Base.jl:380
 [8] include(::Module, ::String) at ./Base.jl:368
 [9] exec_options(::Base.JLOptions) at ./client.jl:296
 [10] _start() at ./client.jl:506
in expression starting at /scratch/7411317/VariantVisualization.jl/viva:131
```

Such VCF was obtained by GATK v3.8 best practices pipeline.
After haplotypecaller, I've ran combineGVCFs, after this, GenotypeGVCF.

I really appreciate if someone could help me here.

Thank you very much for your time.

**Comment by gtollefson** [comment] 2020-10-08 20:26
Hi @Monete I'm going to close this as it's a duplicate of your other issue request.

**Closed by gtollefson** 2020-10-08 20:26 UTC

**Comment by Monete** [comment] 2020-10-08 20:34
Sorry! I think the problem was in my browser. :/

**Comment by gtollefson** [comment] 2020-10-08 20:55
@Monete No worries!
